### ISSUE TITLE
Authentication succeeds, but popup takes a long time to disapppear, error appears in console log

### ISSUE THREAD

**Issue by suzukieng** [Scandit/flow-javascript-sdk#3]
We are using USER_IMPLICIT authentication, with popup: true.

Authentication succeeds, but sometimes (not always) it takes a lot of time (~5-10 seconds) for the popup to disappear and for the app to get notified about successful login. Also, an error appears in the console log (always), see screenshot.

![image](https://user-images.githubusercontent.com/3542048/36889318-c251aee6-1df9-11e8-9bda-90ffa35bd571.png)

**Comment by mjaszczyk** [comment]
Will try to reproduce

**Comment by suzukieng** [comment]
Let me know if you need to see some code snippets from our application.

**Comment by mjaszczyk** [comment]
Unfortunately I cannot reproduce the issue. I was trying using the example app https://github.com/Scandit/flow-javascript-sdk/tree/master/examples/web and `Scandit.Auth.Method.USER_IMPLICIT`. It is always instant. Can you also try if you can reproduce it with the example app?

**Comment by suzukieng** [comment]
Hi @mjaszczyk 
Unfortunately I cannot reproduce it either with the example web app. Also I don't see the aforementioned error in the console.

From the stack trace and location, do you have any idea what could trigger this kind of behavior? We are using the latest Angular 5.

**Comment by mjaszczyk** [comment]
There is a separate project for old Angular https://github.com/Scandit/flow-ng I suggest to check how it can be integrated with the framework. This project is a standalone library and we have not tested it with the latest Angular. Unfortunately i'm not familiar with Angular 5 but I asked my colleagues to help.

**Comment by petradonka** [comment]
@suzukieng could you try to send us a minimal reproducible example? We're not really sure what triggers this error.

**Comment by suzukieng** [comment]
@petradonka @mjaszczyk Sure, will send something as soon as I have time.

**Comment by suzukieng** [comment]
@petradonka  @mjaszczyk  We have not seen this issue in the last two weeks. Closing it.
