### ISSUE TITLE
Updating an object is broken, HTTP POST is used instead of HTTP PUT

### ISSUE THREAD

**Issue by suzukieng** [Scandit/flow-javascript-sdk#6]
According to REST API docs, PUT should be used to update an object.

The JavaScript SDK uses HTTP POST, and fails with a 404 status code.
https://github.com/Scandit/flow-javascript-sdk/blob/2dabc825465c2831cfa7e0acd2dca8c433a63a56/src/db/api/Api.ts#L123

<img width="342" alt="screen shot 2018-08-23 at 10 31 36" src="https://user-images.githubusercontent.com/3542048/44514225-d4906f80-a6bf-11e8-9d0d-2313fe22b41a.png">

**Comment by pdonald** [comment]
Hey, this was fixed by #8
